var zbgx=[];var zbgy=5;var zbgz=25;function zbha(zbhb,zbaf,zbbb){try{zaws(true);zbaz();var zph="";if(zbhb==zair||zbhb==zain||zbhb==zaiq||zbhb==zaip){zph="/";}
else{var zbhc=zarf.znx(zbhb);zbhc=zbhc.zyi;zph=zbhc.zpk;}
var zaty=new Object();zaty[zce]=zarn;zaty[zci]=zbhb;zaty[zcm]=zph;zaty[zcu]=zbaf;zaty[zbe]=false;zaty[zcs]=zbbb;zaty[zbg]=false;var zatz=zrv().zxy(zaty);zbgw(zatz);return;}
catch(zmk){}};function zbgw(zatz){try{if(zatz==null||zatz==undefined){return;}
var zavj=zatz[zbu];var zbhd=zavj[zce];var zbhe=zavj[zcu];var zbhf=zavj[zcs];if(zbhd!=zarn){return;}
var zazq=zazr();if(zatz[zcv]==false){var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=null;zave[zbp]=null;zave[zby]="rf_GetFolderContentResponseSilent";zave[zaz]=zafl.get_folder_content;zave[zci]=zavj[zci];zavf(zave);zays(zazq);return;}
var zbad=zatz["arr"];var zbhg=zavj[zcm];var zbhh=parseInt(zavj[zcu]);var zbhi=parseInt(zavj[zcs]);var zbhj=zkm;var zbhk=zkm;var zbhl=zaqe;var zbhm=zaqe;var zbhn=zaqe;switch(zbhh){case RfObjectType.RFTYPE_SAFENOTE:zbhj=zahw;zbhk=zte("new_safenote");zbhm="table-row";break;case RfObjectType.RFTYPE_PASSCARD:if(zbhi==RfObjectMode.RF_OBJ_MODE_BOOKMARK){zbhj=zahx;zbhk=zte("new_bookmark");zbhl="table-row";zbhm="table-row";}
else{return;}break;case RfObjectType.RFTYPE_IDENTITY:if(zbhi==RfObjectMode.RF_OBJ_MODE_CONTACT){zbhj=zahz;zbhk=zte("new_contact");zbhn="table-row";}
else{zbhj=zahy;zbhk=zte("new_identity");zbhn="table-row";}
break;default:return;}document.getElementById(zaox).innerHTML="<img id='rf_create_obj_img' src='"+zbhj+"' />";document.getElementById(zaow).innerHTML=zbhk;document.getElementById(zaoz).innerHTML=zkm;document.getElementById(zapb).setAttribute(zaqh,zavj[zci]);$("#"+zapb).data(zapw,zbad);document.getElementById(zapb).setAttribute(zapu,false);document.getElementById(zapb).setAttribute(zaqf,zbhi);document.getElementById(zapb).setAttribute(zaqg,zbhh);document.getElementById(zapb).setAttribute(zapv,zbhg);document.getElementById(zapd).style.display=zbhl;document.getElementById(zape).style.display=zbhm;document.getElementById(zapf).style.display=zbhn;if(zbhh==RfObjectType.RFTYPE_SAFENOTE){document.getElementById(zaou).innerHTML=zkm;document.getElementById(zaoy).style.display=zaqe;document.getElementById(zapa).value=zkm;zatq("n_popup_createnote_width",zfp,zfq);}
else if(zbhh==RfObjectType.RFTYPE_PASSCARD){var zop=zatz[zdg];document.getElementById(zaou).innerHTML="Goto URL:";document.getElementById(zaoy).style.display=zaqd;document.getElementById(zapa).value=zop;zatq("n_popup_createnote_width",zfr,zfs);}
else if(zbhh==RfObjectType.RFTYPE_IDENTITY){document.getElementById(zaoy).style.display=zaqe;document.getElementById(zaou).innerHTML=zkm;document.getElementById(zapa).value=zkm;zatq("n_popup_createnote_width",zft,zfu);}
zatr({"s_html":zaqt,"sTitle":zte("create_dlg_title"),"b_pushtoArrays":false,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});setTimeout(function(){zatr({"s_html":document.getElementById(zaoo).innerHTML,"sTitle":zte("create_dlg_title"),"b_pushtoArrays":false,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});$("#"+zapb).data(zapw,zbad);document.getElementById(zapb).setAttribute(zapu,false);document.getElementById(zapb).setAttribute(zaqh,zavj[zci]);document.getElementById(zapb).setAttribute(zaqf,zbhi);document.getElementById(zapb).setAttribute(zaqg,zbhh);document.getElementById(zapb).setAttribute("push_html",false);document.getElementById(zapb).setAttribute(zapv,zbhg);document.getElementById(zapd).style.display=zbhl;document.getElementById(zape).style.display=zbhm;document.getElementById(zapf).style.display=zbhn;if(zbhh==RfObjectType.RFTYPE_SAFENOTE){document.getElementById(zaou).innerHTML=zkm;document.getElementById(zaoy).style.display=zaqe;document.getElementById(zapa).value=zkm;}
else if(zbhh==RfObjectType.RFTYPE_PASSCARD){document.getElementById(zaou).innerHTML="Goto URL:";document.getElementById(zaoy).style.display=zaqd;var zop=zatz[zdg];document.getElementById(zapa).value=zop;}
document.getElementById(zapb).value=zkm;zbho();document.getElementById(zapb).focus();zays(zazq);}
,zask);}catch(zmk){}};function zbhp(){try{document.getElementById(zaoz).innerHTML=zkm;zapc=document.getElementById(zapb);var zri=zapc.value;if(!zri){zapc.focus();return;}
if(zbhq(zri)){document.getElementById(zaoz).innerHTML=zte("create_symbol_restrict");zapc.focus();return;}
var zbhr=parseInt(document.getElementById(zapb).getAttribute(zaqg));var zbhs=parseInt(document.getElementById(zapb).getAttribute(zaqf));var zbht=document.getElementById(zapb).getAttribute(zapu);if(zbht=='false'){var zbhu=$("#"+zapb).data(zapw);for(var zov=0;zov<zbhu.length;zov++){var zra=zbhu[zov];if(parseInt(zra.m_Type)!=zbhr){continue;}
var zpy=zra.m_sName;if(zpy==zri){document.getElementById(zapb).setAttribute(zapu,true);document.getElementById(zaoz).innerHTML=zte("folder_already_exists")+"<br/>"+zte("rewrite_object");return;}
}}var zbhv=document.getElementById(zapb).getAttribute(zapv);var zbhw=document.getElementById(zaov).checked?true:false;var zbhx=document.getElementById(zapb).getAttribute(zaqh);var zauz=new zpc();zauz.znf=zbhs;zauz.m_Type=zbhr;zauz.zpk=zbhv;zauz.m_sName=zri;zauz.zpi=zbhw;var zaus="about:blank";if(zauz.m_Type==RfObjectType.RFTYPE_SAFENOTE){var zbhy=new zbhz();zbhy.zavg=zauz;var zbia=document.getElementById(zaot).value;zbhy.zbib=zbia;}
else if(zauz.m_Type==RfObjectType.RFTYPE_PASSCARD&&zauz.znf==RfObjectMode.RF_OBJ_MODE_BOOKMARK){var zbhy=new zbic();zbhy.zavg=zauz;zaus=document.getElementById(zapa).value;var zbia=document.getElementById(zaot).value;zbhy.zbid=zbia;}
else if(zauz.m_Type==RfObjectType.RFTYPE_IDENTITY){var zvc=document.getElementById(zapg).value;var zvi="";if(zauz.znf==RfObjectMode.RF_OBJ_MODE_DEF){zvi="+";}
var zbhy=new zvk({"Phone prefix mode":0,"World Regions":zvc,"Use for Form Filling":zvi,"App Upload":""
}
);zbhy.zavg=zauz;var zbie=zbhy.zbif();}zatx(true,zaos,[zaoq,zaor],zapb);setTimeout(function(){if(zauz.m_Type==RfObjectType.RFTYPE_SAFENOTE||zauz.m_Type==RfObjectType.RFTYPE_PASSCARD){var zaty=new Object();zaty[zbi]=true;zaty[zce]=zarn;zaty[zci]=0;zaty[zcj]=zbhx;zaty[zdd]=true;zaty[zcy]=zaqy;zaty[zdf]=zaus;zaty[zcz]=zbhy.zavg.zpk;zaty[zbc]=zbhw;zaty[zct]=zbhy;zaty[zck]=zbhy.zavg.m_sName;var zatz=zrv().zya(zaty);zavh(zatz);}
else if(zauz.m_Type==RfObjectType.RFTYPE_IDENTITY){var zaty=new Object();zaty[zdd]=true;zaty[zcy]=zaqy;zaty[zbi]=true;zaty[zdf]=zaus;zaty[zcj]=zbhx;zaty[zci]=0;zaty[zce]=zarn;zaty[zct]=zbhy;var zatz=zrv().zyb(zaty);zavh(zatz);}
},500);}catch(zmk){zatx(false,zaos,[zaoq,zaor],null);}
};function zbig(zawd,zawe){var zacg=zawd||false;zaul(zacg,zawe,"",zacg?true:false);}
;function zbih(zaun){try{zaun=zaun||window.event;var target=(zaun.target)?zaun.target:zaun.scrElement;var zauo=(zaun.charCode)?zaun.charCode:((zaun.zaup)?zaun.zaup:zaun.keyCode);if(zauo==zia){zbhp();}
}catch(zmk){}};var zazq=null;function zavv(zauu,zbii,zbij,zbik){try{zaws(true);zbaz();var zbdx=zarf.znx(zauu);zbdx=zbdx.zyi;if(zbdx){var zaty=new Object();zaty[zci]=zauu;zaty[zce]=zarn;zaty[zdn]=zbii;zaty[zbf]=zbij;zaty[zaz]="view";zaty[zct]=zbdx;zaty[zby]="rf_GetObjectFieldsResponse";var zatz=zrv().zyc(zaty);zbgo(zatz);}
}catch(zmk){}};function zbgo(zatz){try{if(zatz==null||zatz==undefined){return;}
var zato=zatz[zbu];var zbdz=zato[zce];var zauu=zato[zci];if(zarn!=zbdz){return;}
zatx(false,zans,[zanp,zanq],null);var zazq=zazr();if(zatz[zcv]==true){zatq("n_popup_editcard_width",zez,zfa);var zyi=zatz[zco];zatr({"s_html":zaqt,"sTitle":zyi.zavg.m_sName,"b_pushtoArrays":false,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});setTimeout(function(){document.getElementById(zaln).style.display=zaqe;document.getElementById(zalo).style.display=zaqe;document.getElementById(zalq).innerHTML=zkm;var zbil=zbim(zyi,zauu);if(zbil){var zayn=zbil["nWidth"];var zayo=zbil["nHeight"];zatq("n_popup_editcard_width",zayn,zayo);}
var zavk=$("#rfpasscardsection_div").html();zatr({"s_html":zavk,"sTitle":zyi.zavg.m_sName,"b_pushtoArrays":false,"b_show_title":true,"parentId":zkm,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"b_show_back":true});var zbba=zarf.znx(zauu);document.getElementById(zaln).setAttribute(zapo,zauu);document.getElementById(zaln).setAttribute(zaqh,zbba.parentId);$("#"+zaln).data('rfObject',zyi);$("#rf_note_table_td_capton").text(zte("editor_note_lbl"));document.getElementById(zaln).setAttribute("dlg_caption",zyi.zavg.m_sName);$("#edit_pass_pwd_prtoect_lbl").text(zte("savebar_protect_ckbox"));zyi.zavg.zpi==false?document.getElementById("edit_pass_pwd_prtoect_check").removeAttribute("checked"):document.getElementById("edit_pass_pwd_prtoect_check").setAttribute("checked","on");zays(zazq);if(zyi.zavg.znf==RfObjectMode.RF_OBJ_MODE_BOOKMARK||zyi.zavg.m_Type==RfObjectType.RFTYPE_SAFENOTE){setTimeout(function(){document.getElementById(zalv).focus();}
,200);}zbin(zyi.zavg.m_Type,zyi.zavg.znf);return;}
,50);}if(zatz[zcv]==true){return;}var zauz=zarf.znx(zauu);zauz=zauz.zyi;var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=null;zave[zbp]=null;zave[zby]="showPasscardDetails";zave[zct]=zauz;zave[zci]=zauu;zave[zaz]=zafl.edit_view_object;zave[zbs]=zato;zavf(zave);zays(zazq);}
catch(zmk){}};function zbio(){try{var zbip=$("#"+zaln).data('rfObject');if(zdr||zdu){if(zbip.zavg.m_Type==RfObjectType.RFTYPE_PASSCARD){var zbiq=new zbic(zbip);}
else if(zbip.zavg.m_Type==RfObjectType.RFTYPE_SAFENOTE){var zbiq=new zbhz(zbip);}
}else if(zdp){var zbiq=zbip.clone();}var zauu=document.getElementById(zaln).getAttribute(zapo);var zbhx=document.getElementById(zaln).getAttribute(zaqh);var zbir=document.getElementById("input_goto_url").value;if(zdp||zdu){var zbia=document.getElementById(zalv).value;}
else if(zdr){var zbia=document.getElementById(zalv).innerText;}
var zbis=document.getElementById(zalp);if(zbis&&zbis.rows){var zbit=zbis.getAttribute(zaqj);var zbiu=zbis.rows.length;var zbiv=0;if(zbiq.m_lFields){for(var zoy=0;zoy<zbiq.m_lFields.length;++zoy){var zbiw=zbiq.m_lFields[zoy];if(zbiw.m_sName.toString().toLowerCase()!="note$"){zbiv++;}
}}if(zbiu!=zbiv||zbit!=zbiv-1){zbiq.m_lFields.length=0;for(var zov=0;zov<zbiu;zov++){var zbix=zbis.rows[zov];var zpy=zbix.getAttribute(zaqi);var zawl=zbix.getAttribute(zaqm);var zbbf=zbix.getAttribute(zaqn);var zbiy=zbix.getAttribute(zaqk);var zbiz=zbix.getAttribute(zaqo);var zbja=zbix.getAttribute(zaqp);var zbjb=zbix.firstChild.nextSibling.firstChild;var zbjc=zbjb.tagName.toLowerCase()=="input"?zbjb.value:zbjb.innerText;zbiq.zbjd(zpy,zawl,zbbf,zbiy,zbjc,zbiz,zbja);}
}else{for(var zov=0;zov<zbiu;zov++){var zbix=zbis.rows[zov];var zbje=zbix.getAttribute(zaqi);var zbjf=zbix.getAttribute(zaqk);var zbjg=zbix.getAttribute(zaql);var zbjb=zbix.firstChild.nextSibling.firstChild;var zbjc=zbjb.tagName.toLowerCase()=="input"?zbjb.value:zbjb.innerText;for(var zbdr=0;zbdr<zbiv;zbdr++){var zvg=zbiq.m_lFields[zbdr];if(zvg.m_sName.toLowerCase()==zbje.toLowerCase()){if(zvg.m_nOrderIndex==zbjf){zbiq.m_lFields[zbdr].m_sValue=zbjc;break;}
}}}}}var zbjh=document.getElementById("edit_pass_pwd_prtoect_check").checked?true:false;zbiq.zavg.zpi=zbjh;zbiq.m_Type=zbiq.zavg.m_Type;zbiq.znf=zbiq.zavg.znf;if(zbiq.m_Type==RfObjectType.RFTYPE_PASSCARD){zbiq.m_sMatchURL=zbir;zbiq.zbid=zbia;}
else if(zbiq.m_Type==RfObjectType.RFTYPE_SAFENOTE){zbiq.zbib=zbia;}
zatx(true,zalo,[zalw,zalx],zalv);setTimeout(function(){var zaty=new Object();zaty[zdd]=true;zaty[zcy]=zaqw;zaty[zbi]=false;zaty[zdf]=zbir;zaty[zcz]=zbiq.zavg.zpk;zaty[zbc]=zbiq.zavg.zpi;zaty[zci]=zauu;zaty[zce]=zarn;zaty[zcj]=zbhx;zaty[zdn]=null;zaty[zck]=zbiq.zavg.m_sName;zaty[zct]=zbiq;var zatz=zrv().zya(zaty);zavh(zatz);}
,500);}catch(zmk){ztm("ERROR in *POPUP* savepasscard_afteredit: "+zmk.toString(),false);zatx(false,zalo,[zalw,zalx],null);}
};function zavh(zatz){try{if(zatz==null||zatz==undefined){return;}
var zato=zatz[zbu];var zbji=zato[zcy];var zbdz=zato[zce];var zaur=zato[zbi];var zauv=zato[zcj];var zbjj=zato[zci];var zyi=zato[zct];if(zarn!=zbdz){return;}
if(zbji==zaqy){zatx(false,zaos,[zaoq,zaor],null);}
else if(zbji==zaqz){zatx(false,zapk,[zapi,zapj],null);}
else if(zbji==zaqw){zatx(false,zalo,[zalw,zalx],null);}
else if(zbji==zaqx){zatx(false,zamr,[zamh,zami],null);}
else if(zbji==zaqv){zatx(false,zaol,[zaon,zaom],null);}
else if(zbji==zaqu){zatx(false,zans,[zanp,zanq],null);}
if(zatz[zcv]==true){var zbjk=new zpc(zyi.zavg);if(zbjk.m_Type==RfObjectType.RFTYPE_PASSCARD&&zbjk.znf==RfObjectMode.RF_OBJ_MODE_DEF){for(var zne=0;zne<zara.length;++zne){var zot=zara[zne];var zauz=new zpc(zot.zavg);if(zauz.zqz(zbjk)){zara[zne].zavg.zpi=zyi.zavg.zpi;break;}
}}if(zbji==zaqy){if(zbjk.m_Type==RfObjectType.RFTYPE_IDENTITY){var zauz=zyi.zavg;zarm=zarm+1;var zbhx=document.getElementById(zapb).getAttribute(zaqh);var zbbo=new zbbi(zarm,zkm,zauz.m_sName,zkm,null,zauz,zbhx,RfObjectMode.RF_OBJ_MODE_DEF);zarf.znt(zarm.toString(),zbbo);zavu(zarm);}
else{zbig(true,zapb);}}else if(zbji==zaqz){zbjl(true,zapn);}
else if(zbji==zaqw){zbjm(true,zaln);}else if(zbji==zaqx){zbjn(true,zamn);}
else if(zbji==zaqu){if(zbjk.m_Type==RfObjectType.RFTYPE_IDENTITY){var zauz=zyi.zavg;zarm=zarm+1;var zbhx=document.getElementById(zann).getAttribute(zaqh);var zbbo=new zbbi(zarm,zkm,zauz.m_sName,zkm,null,zauz,zbhx,RfObjectMode.RF_OBJ_MODE_DEF);zarf.znt(zarm.toString(),zbbo);if(typeof(zato[zdn])!="undefined"&&zato[zdn]){zavu(zarm,zato[zdn],true);}
else{zavu(zarm);}}else{zawb(true,true);}}else if(zbji==zaqv){if(zbjk.m_Type==RfObjectType.RFTYPE_IDENTITY){var zauz=zyi.zavg;zarm=zarm+1;var zbhx=document.getElementById(zann).getAttribute(zaqh);var zbbo=new zbbi(zarm,zkm,zauz.m_sName,zkm,null,zauz,zbhx,RfObjectMode.RF_OBJ_MODE_DEF);zarf.znt(zarm.toString(),zbbo);if(typeof(zato[zdn])!="undefined"&&zato[zdn]){zavu(zarm,zato[zdn],true);}
else{zavu(zarm);}}else{zawb(false,true);}}return;}
var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=null;zave[zbp]=null;zave[zby]="rf_SaveRfObjectAfterCreateEditResponse";zave[zbi]=zato[zbi];zave[zdf]=zato[zdf];zave[zcj]=zato[zcj];zave[zci]=zato[zci];zave[zct]=zyi;zave[zaz]=zafl.save_object;zavf(zave);}
catch(zmk){}};function zbjm(zawd,zawe){try{var zacg=zawd||false;var zayx=document.getElementById(zaln).getAttribute("dlg_caption");var zawf=zacg?true:false;zaul(zacg,zawe,zayx,zawf);}
catch(zmk){}};function zbjo(zaun){try{var zbjp=document.getElementById(zame);if(!zbjp){return;}
zbjp.style.display=zaqd;var zbis=document.getElementById(zaly);if(zbis){zbis.style.display=zaqe;}
var zbjq=document.getElementById(zalq);if(zbjq){zbjq.style.opacity="0.2";zbjq.setAttribute(zapz,true);}
var zbjr=document.getElementById(zamd);zbjr.selectedIndex=0;var zbjs=document.getElementById(zamc);zbjs.value="";zbjs.focus();var zbjt=document.getElementById("rf_passcard_fieldsactionsAdd_cancelbtn");zbjt.addEventListener("click",zbju,false);var zbjv=document.getElementById("rf_passcard_fieldsactionsAdd_Okbtn");zbjv.addEventListener("click",zbjw,false);}
catch(zmk){}};function zbjw(zaun){var zbjs=document.getElementById(zamc);var zbjx=zbjs.value;zbjx=zbjx.trimLeft();zbjx=zbjx.trimRight();if(!zbjx){zbjs.focus();return;}
var zbjr=document.getElementById(zamd);var zbiz=zbjr.value;var zbis=document.getElementById(zalp);var zbit=zbis.getAttribute(zaqj);zbit=parseInt(zbit)+1;zbis.setAttribute(zaqj,zbit);var zbiw=new zbjy();zbiw.m_sName=zbjx;zbiw.m_sCaption="";zbiw.m_sId="";zbiw.m_sValue="";zbiw.m_field_type=zbiz;zbiw.zbjz=false;zbiw.m_bDefaultValue=false;zbiw.m_nOrderIndex=0;var zbka={}
;if(zbis&&zbis.rows){for(var zov=0;zov<zbis.rows.length;zov++){var zbix=zbis.rows[zov];var zbkb=zbix.getAttribute(zaqi);if(zbjx==zbkb){var zbkc=zbix.getAttribute(zaqk);zbka[zbkc]=true;}
}}var zbiy=0;for(var zoy=0;zoy<zarl;zoy++){if(typeof(zbka[zoy])=="undefined"){zbiy=zoy;break;}
}zbiw.m_nOrderIndex=zbiy;var zbkd=zbke(zbis,zbiw,zbit,"black",false);zbju();zbkd.scrollIntoView();zbkd.firstChild.nextSibling.firstChild.focus();}
;function zbju(zaun){var zbjq=document.getElementById(zalq);if(zbjq){zbjq.style.opacity="1";zbjq.removeAttribute(zapz);}
var zbis=document.getElementById(zaly);if(zbis){zbis.style.display="table";}
var zbjp=document.getElementById(zame);if(zbjp){zbjp.style.display=zaqe;}
};function zbdl(zbkf){try{var zbdk=zbkf.getAttribute(zaqi);var className=zbkf.className;var zbkg=zbkf.getAttribute(zaql);var zbis=document.getElementById(zalp);if(zbis&&zbis.rows){var zbkh=-1;for(var zov=0;zov<zbis.rows.length;zov++){var zbix=zbis.rows[zov];var zbki=zbix.getAttribute(zaql);if(zbki==zbkg){zbkh=zov;break;}
}if(zbkh!=-1){zbis.deleteRow(zbkh);}}}catch(zmk){}
};function zbkj(zaun){var zbkk=this;if(!zbkk){return;}
var zbdk=zbkk.getAttribute(zaqi);var className=zbkk.className;if(className==zamf||className==zamg){var zbkl=document.getElementById(zamb);if(zbkl){zbkl.src=zagn;}
}};function zbkm(zaun){var zbkk=this;var zbdk=zbkk.getAttribute(zaqi);var className=zbkk.className;if(className==zamf||className==zamg){var zbkl=document.getElementById(zamb);if(zbkl){zbkl.src=zaia;}
}};function zbim(zbkn,zbko){try{var zbkp=zbkn.zavg;var zbkq=0;if(zbkn.m_lFields){for(var zov=0;zov<zbkn.m_lFields.length;++zov){var zbiw=zbkn.m_lFields[zov];if(zbiw.m_sName.toString().toLowerCase()!="note$"){zbkq++;}
}}document.getElementById(zaln).style.display=zaqe;document.getElementById(zalu).style.display=zaqe;document.getElementById(zalr).style.display=zaqe;if(zbkp.m_Type==RfObjectType.RFTYPE_PASSCARD){document.getElementById(zalu).style.display=zaqd;document.getElementById(zalr).style.display=zaqd;if(zbkp.znf==RfObjectMode.RF_OBJ_MODE_DEF){if(zdp||zdu){document.getElementById(zals).style.bottom="119px";}
else if(zdr){document.getElementById(zals).style.bottom="117px";}
document.getElementById(zalr).style.top=zkm;document.getElementById(zalr).style.bottom="82px";document.getElementById(zalr).style.height="30px";document.getElementById(zaln).style.display=zaqd;var zbkr=document.getElementById("rf_passcard_grouplegend");document.getElementById("rf_passcard_groupfieldset").style.display=zaqd;zbkr.innerText=zte("Fields");var zbks=document.getElementById(zalq);var zbis=document.createElement("table");zbis.setAttribute("id",zalp);zbis.setAttribute("cellpadding",0);zbis.setAttribute("cellspacing",0);zbis.setAttribute("border",0);zbis.setAttribute(zaqj,zbkq-1);for(var zne=0;zne<zbkn.m_lFields.length;++zne){zbkt(zbis,zbkn.m_lFields[zne],zne);}
zbks.appendChild(zbis);if(zbkp.znf==RfObjectMode.RF_OBJ_MODE_DEF){zbkr.style.background=zbkp.zpi==false?"url('"+zahp+"') no-repeat":"url('"+zaho+"') no-repeat";}
else{zbkr.style.background=zbkp.zpi==false?"url('"+zahq+"') no-repeat":"url('"+zahr+"') no-repeat";}
var zbku="height:28px; min-height:28px;max-height:28px;resize:none;";}
else if(zbkp.znf==RfObjectMode.RF_OBJ_MODE_BOOKMARK){document.getElementById(zalr).style.top="50px";document.getElementById(zalr).style.height="195px";if(zdp||zdu){document.getElementById(zals).style.bottom="82px";}
else if(zdr){document.getElementById(zals).style.bottom="75px";}
var zbku="height:185px; min-height:185px;max-height:185px;resize:none;";}
if(document.getElementById(zalt)!=null){document.getElementById(zalt).innerHTML='<textarea style="'+zbku+'" id="'+zalv+'" >'+zbkn.zbid+'</textarea>';}
document.getElementById("input_goto_url").setAttribute('value',zbkn.m_sGotoURL);var zbkv=document.getElementById("rfpasscardsection_div_first_inner");if(zbkv){zbkv.style.height="293px";zbkv.style.maxHeight="293px";zbkv.style.width="312px";zbkv.style.maxWidth="312px";}
}else if(zbkp.m_Type==RfObjectType.RFTYPE_SAFENOTE){if(zdp||zdu){document.getElementById(zals).style.bottom="40px";}
else if(zdr){document.getElementById(zals).style.bottom="40px";}
document.getElementById(zalr).style.display=zaqd;document.getElementById(zalr).style.top="50px";if(!zard||zard.length==0){zard=zrv().getPrefs();}
var zbep=parseInt(zard[zlh]);var zbeq=parseInt(zard[zlg]);var zbkw=zbeq+5;zbkw+="px";document.getElementById(zalr).style.height=zbkw;if(zdp||zdu){var zbku="width:"+zbep+"px;height:"+zbeq+"px;max-height:450px;max-width:400px;min-height:220px;resize:both;";}
else if(zdr){var zbku="width:"+zbep+"px;height:"+zbeq+"px;max-height:435px;max-width:400px;min-height:220px;resize:both;";}
if(document.getElementById(zalt)!=null){document.getElementById(zalt).innerHTML='<textarea init_width="'+zbep+'" init_height="'+zbeq+'" class="rf_textarea_resizable" style="'+zbku+'" id="'+zalv+'" >'+zbkn.zbib+'</textarea>';}
var zbkv=document.getElementById("rfpasscardsection_div_first_inner");if(zbkv){var zbkx=zbeq+73;zbkv.style.height=zbkx+"px";zbkv.style.maxHeight=zbkx+"px";var zbky=zbep+77;zbkv.style.width=zbky+"px";zbkv.style.maxWidth=zbky+"px";}
var zayn=zbep+90;zayn+="px";var zayo=zbeq+120;zayo+="px";return{"nWidth":zayn,"nHeight":zayo}
;}}catch(zmk){}};function zbkz(zaun){var zbla=document.getElementById(zalv);if(zbla){zblb.call(zbla);}
};function zblc(zuq){var zbep=zuq.clientWidth;var zbeq=zuq.clientHeight;var zbld=document.getElementById(zalr);if(zbld){var zble=zbeq+5;zbld.style.height=zble+"px";}
var zbkv=document.getElementById("rfpasscardsection_div_first_inner");if(zbkv){var zbkx=zbeq+73;zbkv.style.height=zbkx+"px";zbkv.style.maxHeight=zbkx+"px";var zbky=zbep+77;zbkv.style.width=zbky+"px";zbkv.style.maxWidth=zbky+"px";}
zuq.setAttribute("init_height",zbeq);zuq.setAttribute("init_width",zbep);var zayn=zbep+90;zayn+="px";var zayo=zbeq+120;zayo+="px";zatq("n_popup_editcard_width",zayn,zayo);if(!zard||zard.length==0){zard=zrv().getPrefs();}
zard[zlh]=zbep;zard[zlg]=zbeq;if(!zdu){zrv().zavr();}
};function zblb(zaun){try{var zuq=this;if(zuq.clientHeight==0||zuq.clientWidth==0){return;}
var zblf=zuq.getAttribute("init_height");var zblg=zuq.getAttribute("init_width");if(!zblf||!zblg){return;}
if(zblf==zuq.clientHeight&&zblg==zuq.clientWidth){return;}
zblc(zuq);}catch(zmk){}};function zblh(){try{var zbli=document.getElementById("edit_pass_savebook_check").checked?true:false;var zblj=document.getElementById(zaln);if(zbli){zblj.style.opacity="0.3";zblj.setAttribute(zapz,"true");}
else{zblj.style.opacity="1.0";zblj.removeAttribute(zapz);}
}catch(zmk){}};function zbke(zbis,zbiw,zblk,zbll,zblm){try{var zbln=false;var zbix=document.createElement("tr");zbix.setAttribute(zaqi,zbiw.m_sName);zbix.setAttribute(zaqm,zbiw.m_sCaption);zbix.setAttribute(zaqn,zbiw.m_sId);zbix.setAttribute(zaqo,zbiw.m_field_type);zbix.setAttribute(zaql,zblk);zbix.setAttribute(zaqk,zbiw.m_nOrderIndex);zbix.setAttribute(zaqp,zbiw.m_bDefaultValue);var zblo=document.createElement("td");zblo.className="rf_passcard_table_td_capton";zblo.setAttribute("width","100px");var zblp=zbiw.m_sName;var zblq=zbiw.m_nOrderIndex==0?"":"["+zbiw.m_nOrderIndex+"]";zblp+=zblq;var zblr=parseInt(zbiw.m_field_type);switch(zblr){case RfFieldType.RfField_None:zblp+=zkm;break;case RfFieldType.RfFieldText:zblp+=":txt";break;case RfFieldType.RfFieldPassword:zblp+=":pwd";zbln=true;break;case RfFieldType.RfFieldCheckbox:zblp+=":chk";break;case RfFieldType.RfFieldRadioCheck:zblp+=":rch"
break;case RfFieldType.RfFieldRadio:zblp+=":rad"
break;case RfFieldType.RfFieldTextArea:zblp+=":are";break;case RfFieldType.RfFieldSelect:zblp+=":sel";break;default:zblp+=":unk"
break;}
var zbls=document.createElement("div");zbls.className="rf_passfields_table_td_caption_div";zbls.innerText=zblp;zblo.appendChild(zbls);if(zblr==RfFieldType.RfFieldTextArea){zblo.style.verticalAlign="top";}
zblo.style.color=zbll;zblo.title=zblp;zbix.appendChild(zblo);var zblt=document.createElement("td");zblt.setAttribute("align","left");zblt.className="rf_passfields_table_td_value";if(zblr!=RfFieldType.RfFieldTextArea){var zbkk=document.createElement("input");if(zblm){zbkk.setAttribute("readonly",true);}
zbkk.className=zamf;zbkk.setAttribute(zaqi,zbiw.m_sName);zbkk.setAttribute(zaql,zblk);zbkk.setAttribute("type","text");if(zbln){zbkk.setAttribute("type","password");}
zbkk.setAttribute("value",zbiw.m_sValue);zbkk.style.color=zbll;zblt.appendChild(zbkk);}
else{var zblu=document.createElement("textarea");if(zblm){zblu.setAttribute("readonly",zblm);}
zblu.setAttribute(zaqi,zbiw.m_sName);zblu.setAttribute(zaql,zblk);zblu.className=zamg;zblu.style.color=zbll;zblu.innerHTML=zbiw.m_sValue;zblu.innerText=zbiw.m_sValue;zblt.appendChild(zblu);}
zbix.appendChild(zblt);var zblv=document.createElement("td");zblv.setAttribute("width","18px");zblv.setAttribute("align","right");zblv.className="rf_passfields_table_td_pwdshow";if(zbln){var zblw=document.createElement("div");zblw.className="rf_passfields_table_td_pwd_div";zblw.innerHTML="<img id='rf_passfields_table_td_pwd_img"+zblk+"' style='cursor: pointer;' show_symbols_as='"+zapx+"' class='show_pwd_img' width='16' height='16'  src='"+zagz+"' title='Show password values as stars or text' />";zblv.appendChild(zblw);}
zbix.appendChild(zblv);zbis.appendChild(zbix);return zbix;}
catch(zmk){}};function zbkt(zbis,zbiw,zblk){try{var zbll="black";var zblm=false;for(var zov=0;zov<zarp.length;++zov){if(zbiw.m_sName.toString().toLowerCase().indexOf(zarp[zov])!=-1){zbll="grey";zblm=true;}
}if(zbiw.m_sName.toString().toLowerCase()=="note$"){return;}
zbke(zbis,zbiw,zblk,zbll,zblm);}catch(zmk){}};function zblx(){try{zuq=this;var zbly=zuq.getAttribute('show_symbols_as');var zblz=zuq.parentNode.parentNode;var zbma=zblz.previousSibling;var zbkf=zbma.firstChild;var zvv=zbkf.value;zbma.removeChild(zbkf);var zbeo="text";if(zbly==zapy){zbeo="password";zuq.setAttribute('show_symbols_as',zapx);}
else{zuq.setAttribute('show_symbols_as',zapy);}var zbkk=document.createElement("input");zbkk.className=zamf;zbkk.setAttribute("type",zbeo);zbkk.setAttribute("value",zvv);zbkk.style.color="black";zbma.appendChild(zbkk);}
catch(zmk){}};function zbbv(zbbq,zaxt,zbmb){try{zbaz();var zazq=zazr();zatq("n_popup_expiredlg_width",zfh,zfi);zatr({"s_html":zaqt,"sTitle":zte("menu_Save"),"b_pushtoArrays":false,"b_show_title":true,"n_height":zfi,"n_width":zfh,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});setTimeout(function(){var zavk=document.getElementById("manual_save_dlg_div").innerHTML;zatr({"s_html":zavk,"sTitle":zte("menu_Save"),"b_pushtoArrays":false,"n_height":0,"n_width":0,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});if(zbmb==zkm||zbmb==null){zbmb=zaxt;}
document.getElementById(zamm).innerHTML=zkm;document.getElementById(zaml).innerHTML=zkm;document.getElementById(zakv).innerHTML=zkm;var zph=zgw;$("#"+zamn).data("new_rf_obj",zbbq);document.getElementById("manual_save_dlg_section_tree_row").style.display="table-row";document.getElementById(zamn).setAttribute(zcm,zph);document.getElementById(zamn).setAttribute(zaqh,zain);zays(zazq);document.getElementById(zamn).value=zbmb;zbmc();document.getElementById(zamn).focus();var zaty=new Object();zaty[zce]=zarn;zaty[zdb]=zph;zaty[zde]=zamm;var zatz=zrv().zyd(zaty);zbgq(zatz,zamm,zph);}
,zask);}catch(zmk){}};function zbgq(zatz,zbmd,zbme){try{if(zatz==null||zatz==undefined){document.getElementById(zbmd).innerHTML="<b>Loading...</b>";return;}
;var zavj=zatz[zbu];var zbmd=zavj[zde];var zbme=zavj[zdb];var zbdz=zavj[zce];if(zarn!=zbdz){return;}
if(zatz[zcv]!=null){if(typeof(zatz[zcv])=="object"&&zatz[zcv][zbv]==zkd){zauc();return;}
}document.getElementById(zbmd).innerHTML=zkm;zbmf(zatz[zbx],zbme,zbmd);}
catch(zmk){}};function zbmg(zaun){zbmh();zaun=zaun||window.event;var target=(zaun.target)?zaun.target:zaun.scrElement;var zauo=(zaun.charCode)?zaun.charCode:((zaun.zaup)?zaun.zaup:zaun.keyCode);if(zauo==zia){zbmi();return;}
};function zbmj(event){zbmh();};function zbmh(){try{document.getElementById(zaml).innerHTML=zkm;var zri=document.getElementById(zamn).value;if(zri.toString()==zkm){document.getElementById(zamh).setAttribute(zapz,"1");document.getElementById(zamh).className=zaqc;return;}
if(zbhq(zri)){document.getElementById(zaml).innerHTML=zte("create_symbol_restrict");document.getElementById(zamn).focus();return;}
document.getElementById(zamh).removeAttribute(zapz);document.getElementById(zamh).className=zaqb;}
catch(zmk){}};function zbmi(){try{document.getElementById(zaml).innerHTML=zkm;var zri=document.getElementById(zamn).value;if(zbhq(zri)){document.getElementById(zaml).innerHTML=zte("create_symbol_restrict");document.getElementById(zamn).focus();return;}
var zbba=$("#"+zamn).data("new_rf_obj");var zbmk=document.getElementById(zamp).checked;var zbhr=RfObjectType.RFTYPE_PASSCARD;var zbhs=zbmk?RfObjectMode.RF_OBJ_MODE_DEF:RfObjectMode.RF_OBJ_MODE_BOOKMARK;var zbht=true;var zbhv=document.getElementById(zbml).getAttribute("obj_path");if(zbhv==zkm||zbhv==null||zbhv==undefined){zbhv=document.getElementById(zamn).getAttribute(zcm);}
var zbhw=document.getElementById("manual_save_dlg_section_pwd_check").checked?true:false;var zaus=zbba.m_sMatchURL;var zauz=new zpc();zauz.znf=zbhs;zauz.m_Type=zbhr;zauz.zpk=zbhv;zauz.m_sName=zri;zauz.zpi=zbhw;var zbhy=new zbic();zbhy.zavg=zauz;var zbia=zkm;zbhy.zbid=zbia;if(zauz.znf!=RfObjectMode.RF_OBJ_MODE_BOOKMARK){zbhy.m_lFields=zbba.m_lFields;}
zbhy.m_sMatchURL=zaus;zbhy.m_sGotoURL=zaus;zatx(true,zamr,[zamh,zami],zamn);setTimeout(function(){var zaty=new Object();zaty[zdd]=true;zaty[zcy]=zaqx;zaty[zbi]=true;zaty[zdf]=zaus;zaty[zcz]=zbhy.zavg.zpk;zaty[zbc]=zbhw;zaty[zce]=zarn;zaty[zci]=0;zaty[zcj]=zain;zaty[zck]=zbhy.zavg.m_sName;zaty[zct]=zbhy;zaty[zdn]=null;var zatz=zrv().zya(zaty);zavh(zatz);}
,500);}catch(zmk){zatx(false,zamr,[zamh,zami],null);}
};function zbjn(zawd,zawe){var zacg=zawd||false;zbmm();zaul(false,zawe,"",false);}
;function zbch(zavy){try{if(zavy==undefined){zavy=false;}
var zbmn=0;var zbmo=document.getElementById("rf_phonepref_combo");if(zbmo){zbmn=zbmo.selectedIndex;}
if(zarj==zkm){return;}var zauz=new zpc();zauz.m_Type=RfObjectType.RFTYPE_IDENTITY;zauz.zpk=zari;zauz.m_sName=zarj;var zaty=new Object();zaty[zce]=zarn;zaty[zcp]=zbmn;zaty[zct]=zauz;zaty[zbj]=zavy;zaty[zbf]=null;zaty[zdm]=null;var zatz=zrv().zye(zaty);zavt(zatz);}
catch(zmk){}};function zavt(zatz){try{if(zatz==null||zatz==undefined){return;}
var zato=zatz[zbu];var zbdz=zato[zce];if(zarn!=zbdz){return;}
if(zatz[zcv]==true){zaxf();return;}zatx(false,zans,[zanp,zanq],null);var zauz=zato[zct];zarm=zarm+1;var zbbo=new zbbi(zarm,zkm,zauz.m_sName,zkm,null,zauz,zkm,RfObjectMode.RF_OBJ_MODE_DEF);zarf.znt(zarm.toString(),zbbo);var zazq=zazr();var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=null;zave[zbp]=null;zave[zby]="click_identity";zave[zcp]=zato[zcp];zave[zct]=zauz;zave[zci]=zarm;zave[zaz]=zafl.fill_identity_object;zave[zbj]=zato[zbj];zavf(zave);zays(zazq);}
catch(zmk){}};function zavu(zauu,zbii,zbij){try{zbaz();var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;var zaty=new Object();zaty[zci]=zauu;zaty[zbf]=zbij;zaty[zaz]="view";zaty[zdn]=zbii;zaty[zct]=zauz;zaty[zce]=zarn;zaty[zby]="showIdentity_result";var zatz=zrv().zyc(zaty);zbgp(zatz);}
catch(zmk){}};function zbgp(zatz){try{if(zatz==null||zatz==undefined){return;}
var zauu=zatz[zbu][zci];var zbii=zatz[zbu][zdn];var zbba=zarf.znx(zauu);zatx(false,zans,[zanp,zanq],null);if(zatz[zcv]==true){var zbmp=zuy(zatz[zco].zbmq,zbba.zyi.znf==RfObjectMode.RF_OBJ_MODE_CONTACT);zatz[zco]=zbmp;var zbmr=zbms(zatz[zco]);zbmr+=document.getElementById("rfIdentitysection_btns").innerHTML;zatr({"s_html":zbmr,"b_pushtoArrays":false,"b_show_title":true,"b_show_back":true,"sTitle":zbba.zyi.m_sName,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});zbmt();zatq("n_popup_createnote_width",zgb,zgc);document.getElementById(zapn).setAttribute("dlg_caption",zbba.zyi.m_sName);document.getElementById(zapn).setAttribute(zapo,zauu);if(zbii){document.getElementById(zapn).setAttribute("aid_mp",zbii);}
document.getElementById(zapn).setAttribute(zaqh,zbba.parentId);var zbmu=zatz[zco].clone();zbmu.zavg=new zpc(zbba.zyi);$("#"+zapn).data("rfObject",zbmu);zbmv.call(document.getElementById('tabperson'));return;}
var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=null;zave[zbp]=null;zave[zby]="showIdentity";zave[zci]=zauu;zave[zct]=zauz;zave[zaz]=zafl.edit_view_object;zavf(zave);}
catch(zmk){}};function zbjl(zawd,zawe){try{var zacg=zawd||false;var zayx=document.getElementById(zapn).getAttribute("dlg_caption");zaul(zacg,zawe,zayx,false);}
catch(zmk){}};function zbmw(){try{zatx(true,zapk,[zapi,zapj],null);var zbmu=$("#"+zapn).data("rfObject");var zbmx=document.getElementById(zapn).getAttribute(zapo);var zbhx=document.getElementById(zapn).getAttribute(zaqh);var zbmy=document.getElementById(zapn).getAttribute("aid_mp");var zbmz=document.getElementById(zapn);var zbna=zbmz.getElementsByTagName("select");for(var zov=0;zov<zbna.length;zov++){zbnb(zbna[zov],zbmu);}
var zbnc=zbmz.getElementsByTagName("input");for(var zov=0;zov<zbnc.length;zov++){zbnb(zbnc[zov],zbmu);}
var zbnd=zbmz.getElementsByTagName("textarea");for(var zov=0;zov<zbnd.length;zov++){zbnb(zbnd[zov],zbmu);}
zbmu.zbne.zbnf();var zbng=document.getElementById(zapl);if(zbng){var children=zbng.rows;for(var zov=0;zov<children.length;zov++){var zbnh=children[zov];if(zbnh.getAttribute("id")&&zbnh.getAttribute("id")=="identity_customfieldsRow_labels"){continue;}
var zbni=zbnh.children;var zbnj=zbni[0].firstChild.value;var zbnk=zbni[1].firstChild.value;var zbnl=zbni[2].firstChild.value;zbnl=zbnl.split(String.fromCharCode(10)).join("; ");if(zbnj!=""&&zbnk!=""){zbmu.zwa(zbnj,zbnl,zbnk,false);}
}}setTimeout(function(){var zaty=new Object();zaty[zdd]=true;zaty[zcy]=zaqz;zaty[zbi]=false;zaty[zdf]="about:blank";zaty[zct]=zbmu;zaty[zdn]=zbmy;zaty[zce]=zarn;zaty[zcj]=zbhx;zaty[zci]=zbmx;var zatz=zrv().zyb(zaty);zavh(zatz);}
,500);}catch(ztl){}};function zbnb(zbnm,zbmu){var zbnn=zbnm.getAttribute("isCustom");if(zbnn=="true"){return false;}
var zwb=zbnm.value;var zbno=zbnm.getAttribute("identity-field-value");if(zbno==zwb){return false;}
var zbnp=zbnm.getAttribute("identity-field-id");var zvg=zbmu.zbne.zbnq[zbnp];if(!zvg){return false;}
var zvz=zbnm.getAttribute("identity-field");var zbnr=zbnm.getAttribute("instance");zvg.zbns(zbnr,zwb,false);return true;}
;function zbms(zabk){try{document.getElementById(zaph).innerHTML=zkm;zasj="";var zbnt=document.createElement("div");zbnt.id=zapn;zbgx.length=0;var zbnu=zabk.zacf();var zbnv=zbnu.zack;for(var zbnw=0;zbnw<zbnv.length;zbnw++){zbgx.push(zbnv[zbnw].m_sName);}
if(typeof(zbnu.zbnx)!="undefined"&&zbnu.zbnx){zbgx.push("Custom");}
var zbny=document.createElement("div");zbny.id="div_tabs";zbnt.appendChild(zbny);for(var zov=0;zov<zbgx.length;zov++){var zbnz=document.createElement("div");var zboa=zbgx[zov].toLowerCase();zboa=zboa.split(' ').join('_');zbnz.id="tab"+zboa;zbnz.className="rf_tab";zbnz.setAttribute("title",zbgx[zov]);zbnz.setAttribute("groupname",zboa);var zbob="images/group_"+zboa+".png";if(zboa=="custom"){zbob="images/group_custom.ico";}
zbnz.innerHTML="<img src='"+zbob+"'>";zbny.appendChild(zbnz);}
var zboc=document.createElement("div");zboc.style.clear="both";zbny.appendChild(zboc);var zbod=document.createElement("div");zbod.id="ff_content";zbnt.appendChild(zbod);for(var zoy=0;zoy<zbgx.length;zoy++){var zboa=zbgx[zoy].toLowerCase();zboa=zboa.split(' ').join('_');var zboe=document.createElement("div");zboe.id="pane"+zboa;zboe.setAttribute("groupname",zboa);zboe.className="rf_pane";zbod.appendChild(zboe);}
document.getElementById(zaph).appendChild(zbnt);for(var zne=0;zne<zbnv.length;++zne){var zvd=zbnv[zne];var zbof=zvd.m_sName;var zbog=zbnu.zboh(zbof);for(var zboi=0;zboi<zbog.length;zboi++){zboj(zvd,zbog[zboi],zbnu,zbog.length);}
}if(typeof(zbnu.zbnx)!="undefined"&&zbnu.zbnx){zboj(zbnu.zbnx,"Main",zbnu,1);}
return document.getElementById(zaph).innerHTML;}catch(zmk){}
};function zbok(){var zbng=document.getElementById(zapl);var children=zbng.rows;if(children.length>zbgz){return;}
var zbmu=$("#"+zapn).data("rfObject");var zbnu=zbmu.zbne;zbol(null,zbng,zbnu);}
;function zbol(zvg,zbom,zbnu){var zbcs=document.createElement('tr');zbcs.setAttribute('class',"custom_field_row");var zbcr=document.createElement('td');var zbon=document.createElement("input");var zvz=!zvg?"":zvg.zadp;zbon.value=zvz;zbon.setAttribute('value',zvz);zbon.setAttribute('class',"custom_field_singletextbox");zbon.setAttribute("isCustom","true");zbcr.appendChild(zbon);zbcs.appendChild(zbcr);zbcr=document.createElement('td');var zboo=document.createElement("input");var zwb=!zvg?"":zvg.zadh(zbnu,"Main");zboo.setAttribute('value',zwb);zboo.value=zwb;zboo.setAttribute('class',"custom_field_singletextbox");zboo.setAttribute("isCustom","true");zbcr.appendChild(zboo);zbcs.appendChild(zbcr);var zvu=!zvg?"":zvg.zadc().zadg();zvu=zvu.split("; ").join("\n");zbcr=document.createElement('td');zbcr.setAttribute("colspan","2");var zbop=document.createElement("textarea");zbop.setAttribute("multiline","true");zbop.setAttribute("flex","1");zbop.setAttribute("value",zvu);zbop.setAttribute("isCustom","true");zbop.setAttribute('class',"custom_field_multitextbox");zbcr.appendChild(zbop);zbcs.appendChild(zbcr);zbom.appendChild(zbcs);}
;function zboj(zboq,zacv,zbnu,zbor){try{var zbof=zboq.m_sName;var zbos=null;var zbot=document.createElement("fieldset");zbot.className="rf_identity_groupfieldset";var zbkr=document.createElement("legend");zbkr.className="rf_identity_grouplegend";var zbou=zbor>1?" - "+zacv:"";zbkr.innerText=zboq.m_sName+zbou;if(zbof.toLowerCase()=='person'){zbkr.innerText=zte("Person")+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("paneperson");}
else if(zbof.toLowerCase()=='business'){zbkr.innerText=zte("Business")+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panebusiness");}
else if(zbof.toLowerCase()=='location'){zbkr.innerText=zte("location")+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panelocation");}
else if(zbof.toLowerCase()=='credit card'){zbkr.innerText=zte("credit_card")+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panecredit_card");}
else if(zbof.toLowerCase()=='bank account'){zbkr.innerText=zte("bank_account")+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panebank_account");}
else if(zbof.toLowerCase()=='passport'){zbkr.innerText=zbof+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panepassport");}
else if(zbof.toLowerCase()=='car'){zbkr.innerText=zbof+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panecar");}
else if(zbof.toLowerCase()=='default password'){zbkr.innerText=zte("Authentication")+zbou;zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panedefault_password");}
else{zbkr.innerText=zte("Custom");zbkr.style.background="url('"+zaii+"') no-repeat";zbos=document.getElementById("panecustom");}
zbot.appendChild(zbkr);var zbov=document.createElement("fieldset");zbov.className="rf_identity_table_innerset";zbot.appendChild(zbov);var zbow=document.createElement("legend");zbov.appendChild(zbow);var zbis=document.createElement("table");zbis.className="rf_identity_table";if(zbof=="Custom"){zbis.id=zapl;}
zbis.setAttribute("cellpadding",0);zbis.setAttribute("cellspacing",0);zbis.setAttribute("border",0);var zbox=null;var zboy="";var zboz=null;for(var zne=0;zne<zboq.m_lFields.length;++zne){var zbnj=zboq.m_lFields[zne];var zvg=zbnu.zada(zbnj);if(!zvg){continue;}
var zadb=zvg.zbpa;var zbpb=false;if(zbof=="Location"&&zbnj=="Country"){zbpb=true;}
else if(zadb.zadd()){continue;}var zawl=zadb.m_sCaption;if(zbof=="Location"&&zbnj=="Country"){zawl="Country";}
if(zawl.length&&zawl=="$Note$"){zboy=zvg.zadh(zbnu,zacv);zboz=document.createElement("textarea");zboz.setAttribute("multiline","true");zboz.setAttribute("class","identity_field_notearea");zboz.setAttribute("value",zboy);zboz.value=zboy;zboz.setAttribute('instance',zacv);zboz.setAttribute("isCustom","false");zboz.setAttribute("identity-field",zbnj);zboz.setAttribute("identity-field-value",zboy);zboz.setAttribute("identity-field-id",zvg.zbpc);continue;}
var zbpd=false;if(zawl.length&&zawl[0]=='_'){zbpd=true;zawl=zawl.substr(1);}
else{zbox=null;}var zbpe=false;if(zawl.length&&zawl[0]==':'){zbpe=true;zawl=zawl.substr(1);}
var zbpf=0;if(zawl.length&&zawl.match(new RegExp("^(.*)\\@(\\d+)(.*)$"))){zbpf=parseInt(RegExp.$2);zawl=RegExp.$1+RegExp.$3;}
var zbpg="";if(zawl.length&&zawl.match(new RegExp("^\\s*(.*)\\^(.*)$"))){zbpg=RegExp.$2;zawl=RegExp.$1||RegExp.$2;}
if(zawl.length&&zawl.indexOf("#")==0){zawl=zawl.substr(1);}
var zwb=zvg.zadh(zbnu,zacv);if(zbpd){if(zbox){var zbph=zbox.rows[0];zbox.style.width="10%";var zbpi=zbox.rows[1];var zbpj=false;if(zawl&&zbpg&&zawl!=zbpg){zbpj=true;}
if(zbpg){if(zbpi){var zbpk=document.createElement("td");if(zbpj){var zbpl=document.createElement("td");zbpi.appendChild(zbpl);}
zbpk.className="rf_identity_lower_row_td";zbpk.style.paddingLeft="3px";zbpk.innerText=zbpg;zbpi.appendChild(zbpk);zbox.style.marginBottom="3px";}
}if(zawl&&zawl!=zbpg){var zbpm=document.createElement("td");zbpm.className="rf_identity_table_td_capton_next";var zbpn=document.createElement("div");zbpn.className="rf_identity_table_td_div_capton_next";if(zbpg&&zawl=="/"){zbpn.style.marginLeft="1px";zbpn.style.width="5px";}
zbpn.innerText=zawl||zvg.zadp;zbpn.setAttribute("title",zawl||zvg.zadp);zbpm.appendChild(zbpn);zbph.appendChild(zbpm);}
var zbpo=document.createElement("td");zbpo.style.paddingLeft="3px";if(zadb&&zadb.zbpp==1){var zbpq=zbpr("select","rf_identity_table_select",zbof,zbnj,zwb,zacv,zvg);zbpo.appendChild(zbpq);zbps(zbpq,zwb);}
else{var zbkk=zbpr("input","rf_identity_table_input",zbof,zbnj,zwb,zacv,zvg);if(zadb.zbpt>0){var zbep=zadb.zbpt*zbpu+2;zbpo.style.width=zbep+"px";}
zbpo.appendChild(zbkk);}zbph.appendChild(zbpo);}else{throw"There is No Prev TABLE!"
}
}else{var zbix=document.createElement("tr");zbis.appendChild(zbix);var zblo=document.createElement("td");zblo.className="rf_identity_table_td_capton";var zbls=document.createElement("div");zbls.className="rf_identity_table_td_div_capton";if(zbof=="Location"&&zbnj=="Country"){zbls.style.color="Grey";}
zbls.innerText=zawl||zvg.zadp;zbls.setAttribute("title",zawl||zvg.zadp);zblo.appendChild(zbls);zbix.appendChild(zblo);var zbpv=document.createElement("td");zbpv.className="rf_identity_table_td_value";var zbpw=document.createElement("table");zbpw.className="rf_identity_td_value_innerTable";zbpw.setAttribute("cellpadding","0");zbpw.setAttribute("cellspacing","0");zbpv.appendChild(zbpw);zbox=zbpw;var zbpx=document.createElement("tr");zbpx.className="rf_identity_upper_row";zbpw.appendChild(zbpx);if(zbpg){var zbpy=document.createElement("tr");zbpy.className="rf_identity_lower_row";zbpw.appendChild(zbpy);var zbpz=document.createElement("td");zbpz.className="rf_identity_lower_row_td";zbpz.innerText=zbpg;zbpy.appendChild(zbpz);}
var zbqa=document.createElement("td");if(zadb&&zadb.zbpp==1){if(zbof=="Location"&&zbnj=="Country"){var zbkk=zbpr("input","rf_identity_table_input",zbof,zbnj,zwb,zacv,zvg);zbqa.appendChild(zbkk);}
else{var zbpq=zbpr("select","rf_identity_table_select",zbof,zbnj,zwb,zacv,zvg);zbqa.appendChild(zbpq);zbps(zbpq,zwb);}
}else{var zbkk=zbpr("input","rf_identity_table_input",zbof,zbnj,zwb,zacv,zvg);if(zadb.zbpt>0){var zbep=zadb.zbpt*zbpu+10;zbqa.style.width=zbep+"px";}
zbqa.appendChild(zbkk);}zbpx.appendChild(zbqa);zbix.appendChild(zbpv);}
}if(zboz){var zbcs=document.createElement("tr");var zblo=document.createElement("td");zblo.className="rf_identity_table_td_capton";var zbls=document.createElement("div");zbls.className="rf_identity_table_td_div_capton";zbls.innerText=zte("editor_note_lbl");zbls.setAttribute("title",zte("editor_note_lbl"));zblo.appendChild(zbls);zbcs.appendChild(zblo);var zbqb=document.createElement("td");zbqb.className="rf_identity_table_td_value";zbqb.appendChild(zboz);zbcs.appendChild(zbqb);zbis.appendChild(zbcs);}
if(zbof=="Custom"){var zbqc=zbnu.zadj();var zbqd=document.createElement("tr");zbqd.id="identity_customfieldsRow_labels";var zbqe=document.createElement("td");zbqe.innerText="Field Name";zbqd.appendChild(zbqe);zbqe=document.createElement("td");zbqe.innerText="Field Value";zbqd.appendChild(zbqe);zbqe=document.createElement("td");zbqe.innerText="Other Match Strings";zbqd.appendChild(zbqe);zbqe=document.createElement("td");zbqe.setAttribute("align","right");var zbqf=document.createElement("input");zbqf.id=zapm;zbqf.setAttribute("type","button");zbqf.setAttribute("title","Add new Custom Field");zbqe.appendChild(zbqf);zbqd.appendChild(zbqe);zbis.appendChild(zbqd);var zbqg=zbqc<zbgy?zbgy:zbqc+1;for(var znh=0;znh<zbqg;znh++){var zvg=znh<zbqc?zbnu.zadl(znh):null;zbol(zvg,zbis,zbnu);}
}zbov.appendChild(zbis);if(zbos){zbos.appendChild(zbot);}
}catch(zmk){}};function zbqh(zauu){try{zbaz();var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;zari=zauz.zpk;zarj=zauz.m_sName;var zaty=new Object();zaty[zbd]=true;zaty[zcm]=zari;zaty[zcg]=zarj;zrv().zyk(zaty);}
catch(zmk){}};function zbbe(zauu,zavy){try{var zbmn=0;var zbmo=document.getElementById("rf_phonepref_combo");if(zbmo){zbmn=zbmo.selectedIndex;}
zbaz();var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;var zaty=new Object();zaty[zce]=zarn;zaty[zcp]=zbmn;zaty[zct]=zauz;zaty[zbj]=zavy;zaty[zbf]=null;zaty[zdm]=null;var zatz=zrv().zye(zaty);zavt(zatz);}
catch(zmk){}};function zbps(zuq,zwb){var zbfw=-1;for(var zov=0;zov<zuq.options.length;zov++){var zbqi=zuq.options[zov];if(zbqi.value==zwb){zbfw=zov;break;}
}zuq.selectedIndex=zbfw;zuq.setAttribute("setSelectedIndex",zbfw);}
;var zbpu=7;function zbpr(zbqj,zbqk,zbof,zbnj,zwb,zacv,zvg){var zadb=zvg.zbpa;var zuq=document.createElement(zbqj);if(zbqj=="input"||zbqj=="select"){zuq.setAttribute("identity-field",zbnj);zuq.setAttribute("isCustom","false");zuq.setAttribute("instance",zacv);zuq.setAttribute("identity-field-value",zwb);zuq.setAttribute("identity-field-id",zvg.zbpc);zuq.className=zbqk;if(zbof=="Location"&&zbnj=="Country"){zuq.setAttribute("readonly",true);zuq.style.color="Grey";}
if(zbqj=="input"){zuq.setAttribute("value",zwb);if(zadb.zbpt>0){var zbep=zadb.zbpt*zbpu;zuq.style.width=zbep+"px";zuq.style.minWidth=zbep+"px";zuq.setAttribute("maxlength",zadb.zbpt);}
}else{var zbql=document.createElement("option");zbql.setAttribute("label",zkm);zbql.setAttribute("value",zkm);zbql.setAttribute("class","identity_field_select_option");zuq.add(zbql,null);for(var zov=0;zov<zadb.zbqm.length;zov++){var zatc=document.createElement("option");var zvv=zadb.zbqm[zov].zbqn;zvv=zvv=="{UserDefined}"?"(Unlisted)":zvv;zvv=zvv=="{UserDefinedShort}"?"(Unl)":zvv;zatc.setAttribute("label",zvv);zatc.setAttribute("value",zvv);zatc.setAttribute("class","identity_field_select_option");zuq.add(zatc,null);}
}}return zuq;};function zbqo(zauz,zbqp,zbqq,zri,zrj,zbqr){try{if(zauz.m_Type!=RfObjectType.RFTYPE_IDENTITY){return;}
if(zbqp==zarj&&zbqq==zari){zarj=zri;zari=zrj;var zaty=new Object();zaty[zbd]=zbqr;zaty[zcm]=zari;zaty[zch]=zbqp;zaty[zcn]=zbqq;zaty[zcg]=zarj;zrv().zyk(zaty);}
}catch(zmk){}};function zut(zuu,zuv){var zuw=zuu;var zux=zuv/10;zuw.css({"opacity":zux}
);if(zuv==1){zuw.show();zuw.css({"opacity":"0.3"});}
};function zbqs(zuu,zuv){var zux=1-zuv;$(zuu).css({zuv:zux}
);if(zuv==1){$(".rf_pane").hide();}};function zbqt(){var zbqu=this;if(zbqu.getAttribute("id")==zasj){return;}
zbqu.style.backgroundColor="#eee";};function zbqv(){var zbqu=this;if(zbqu.getAttribute("id")==zasj){return;}
zbqu.style.backgroundColor="#DCDFE6";};function zbmv(){var zuu=this.id;var zbqw=$("#"+zuu.replace(new RegExp("pane"),"tab"));$(".rf_tab").css({"background":"#DCDFE6","border":"1px solid #aaa","border-bottom":"1px solid grey"}
);zbqw.css({"background":"#fff","border":"1px solid grey","border-bottom":"1px solid white"}
);$(".rf_pane").hide();var zbqx=zbqw.attr("groupname");var zbqy="pane"+zbqx;var zuw=$("#"+zbqy);setTimeout(function(){zut(zuw,1);}
,0);setTimeout(function(){zut(zuw,4);},200);setTimeout(function(){zut(zuw,5);}
,250);setTimeout(function(){zut(zuw,6);},300);setTimeout(function(){zut(zuw,7);}
,350);setTimeout(function(){zut(zuw,8);},400);setTimeout(function(){zut(zuw,9);}
,450);setTimeout(function(){zut(zuw,10);},500);zasj=zuu;return false;}
;function zbqz(zauu){try{zaws(true);zbaz();var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zazq=zazr();var zbhx=zbba.parentId;var zauz=zbba.zyi;var zbra;if(parseInt(zauz.m_Type)==RfObjectType.RFTYPE_FOLDER){if(!zdu){var zaty=new Object();zaty[zce]=zarn;zaty[zcm]=zauz.zpk;zaty[zcu]=7;zaty[zbe]=false;zaty[zbg]=true;zaty[zcg]=zauz.m_sName;var zatz=zrv().zxy(zaty);zbra=zatz[zbb];}
}zatq("n_popup_deleteobj_width",zfb,zfc);zatr({"s_html":zaqt,"sTitle":zte("Delete"),"b_pushtoArrays":false,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});setTimeout(function(){var zavk=document.getElementById(zakn).innerHTML;zatr({"s_html":zavk,"sTitle":zte("Delete"),"b_pushtoArrays":true,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});var zpy=zauz.m_sName;if(zpy.length>zarr){zpy=zpy.substring(0,zarr-3)+"...";}
document.getElementById(zakm).innerText=zte("alert_delete_msg")+" \'"+zpy+"\' ?";document.getElementById(zakm).setAttribute(zapo,zauu);document.getElementById(zakm).setAttribute(zaqh,zbhx);document.getElementById(zako).innerHTML=zkm;if(zbra&&zbra.length){document.getElementById(zako).innerHTML="Folder is not empty!";}
zays(zazq);zbrb();},zask);return;}catch(zmk){}};function zbrc(zawd,zawe){var zacg=zawd||false;zaul(zacg,zawe,zte("Delete"),true);}
;function zbrd(event){try{var zauu=document.getElementById(zakm).getAttribute(zapo);var zbba=zarf.znx(zauu);var zauz=zbba.zyi;document.getElementById(zako).innerHTML=zkm;zatx(true,zakp,[zaki,zakk],zakm);setTimeout(function(){var zaty=new Object();zaty[zct]=zauz;zaty[zce]=zarn;zaty[zci]=zauu;var zatz=zrv().zyo(zaty);zbgs(zatz);}
,500);}catch(zmk){zatx(false,zakp,[zaki,zakk],null);}
};function zbgs(zatz){try{if(zatz==null||zatz==undefined){return;}
var zato=zatz[zbu];var zbdz=zato[zce];var zauu=zato[zci];if(zarn!=zbdz){return;}
zatx(false,zakp,[zaki,zakk],null);document.getElementById(zako).innerHTML=zkm;if(zatz[zcv]==true){var zbre=new zpc(zato[zct]);if(zbre.m_Type==RfObjectType.RFTYPE_IDENTITY&&zbre.znf==RfObjectMode.RF_OBJ_MODE_DEF){zbqo(zato[zct],zato[zct].m_sName,zato[zct].zpk,zkm,zkm,true);}
if(zbre.m_Type==RfObjectType.RFTYPE_PASSCARD&&zbre.znf==RfObjectMode.RF_OBJ_MODE_DEF){for(var zne=0;zne<zara.length;++zne){var zot=zara[zne];var zauz=new zpc(zot.zavg);if(zauz.zqz(zbre)){if(zara.splice){zara.splice(zne,1);}
break;}}for(var zne=0;zne<zarb.length;++zne){var zot=zarb[zne];var zauz=new zpc(zot);if(zauz.zqz(zbre)){if(zarb.splice){zarb.splice(zne,1);}
break;}}}zbrc(true,zakm);return;}if(zatz[zbv]==zke){document.getElementById(zako).innerText=zte("file_not_found");}
var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=document.getElementById(zako);zave[zbp]=document.getElementById(zako);zave[zby]="rf_DeleteObjectResponse";zave[zaz]=zafl.delete_object;zave[zci]=zauu;zavf(zave);}
catch(zmk){zatx(false,zakp,[zaki,zakk],null);}};function zbrf(zauu){try{zaws(true);zbaz();var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;if(zauz.m_Type==RfObjectType.RFTYPE_FOLDER){zbrg(zbba,zauu);return;}
if(zauz.m_Type==RfObjectType.RFTYPE_PASSCARD||zauz.m_Type==RfObjectType.RFTYPE_IDENTITY||zauz.m_Type==RfObjectType.RFTYPE_SAFENOTE){zbrh(zbba,zauu);return;}
}catch(zmk){}};function zbrh(zbba,zauu){try{zbaz();var zazq=zazr();zatq("n_popup_renamedlg_width",zfj,zfk);zatr({"s_html":zaqt,"sTitle":zte("Rename"),"b_pushtoArrays":false,"b_show_title":true,"n_height":zfk,"n_width":zfj,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});setTimeout(function(){var zavk=$("#rfpcard_rename_section_div").html();zatr({"s_html":zavk,"sTitle":zte("Rename"),"b_pushtoArrays":true,"n_height":0,"n_width":0,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});var zauz=zbba.zyi;var zbhx=zbba.parentId;var zpy=zauz.m_sName;var zph=zauz.zpk;var zblk=zpy.lastIndexOf("/");if(zblk!=-1){zpy=zpy.substr(zblk+1);if(zph==zkm){zph=zgw+zauz.m_sName.substr(0,zblk);}
}if(zph==zkm){zph=zgw;}document.getElementById(zakv).innerHTML=zkm;document.getElementById(zakv).innerHTML=zkm;document.getElementById(zamm).innerHTML=zkm;var zbri=zbrj(zauz);document.getElementById(zakq).innerText=zte("rename_passcard");document.getElementById(zakq).style.background="url('"+zbri.zbrk+"') no-repeat";document.getElementById(zakr).innerText=zbri.text+":";document.getElementById(zakt).setAttribute("defaultValue",zpy);document.getElementById(zakt).setAttribute(zcm,zph);document.getElementById(zakt).setAttribute(zapo,zauu);document.getElementById(zakt).setAttribute(zaqh,zbhx);document.getElementById(zaky).innerHTML=zkm;document.getElementById(zakt).value=zpy;document.getElementById(zakt).focus();zays(zazq);zbrl();var zaty=new Object();zaty[zce]=zarn;zaty[zdb]=zph;zaty[zde]=zakv;var zatz=zrv().zyd(zaty);zbgq(zatz,zakv,zph);}
,zask);}catch(zmk){}};function zbrm(){try{document.getElementById(zaky).zbrn=zkm;var zri=document.getElementById(zakt).value;if(zbhq(zri)){document.getElementById(zaky).innerHTML=zte("create_symbol_restrict");document.getElementById(zakt).focus();return;}
var zauu=document.getElementById(zakt).getAttribute(zapo);var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;var zbqq=zauz.zpk;var zbqp=zauz.m_sName;zauz.m_sName=document.getElementById(zakt).getAttribute("defaultValue");var zrj=document.getElementById(zbml).getAttribute("obj_path");if(zrj==zkm||zrj==null||zrj==undefined){zrj=document.getElementById(zakt).getAttribute(zcm);}
zauz.zpk=document.getElementById(zakt).getAttribute(zcm);zatx(true,zalb,[zald,zale,zaks],zakt);setTimeout(function(){var zaty=new Object();zaty[zct]=zauz;zaty[zci]=zauu;zaty[zce]=zarn;zaty[zch]=zbqp;zaty[zcn]=zbqq;zaty[zcg]=zri;zaty[zcm]=zrj;zaty["b_cut_copy"]=false;var zatz=zrv().zxz(zaty);zbgm(zatz);}
,500);}catch(zmk){zatx(false,zalb,[zald,zale,zaks],null);}
};function zbro(zaun){zbrp();zaun=zaun||window.event;var target=(zaun.target)?zaun.target:zaun.scrElement;var zauo=(zaun.charCode)?zaun.charCode:((zaun.zaup)?zaun.zaup:zaun.keyCode);if(zauo==zia){zbrm();return;}
};function zbrp(){try{document.getElementById(zaky).innerHTML=zkm;var zri=document.getElementById(zakt).value;var zbrq=document.getElementById(zakt).getAttribute("defaultValue");var zbrr=document.getElementById(zakt).getAttribute(zcm);if(zri.toString()==zkm){document.getElementById(zald).setAttribute(zapz,"1");document.getElementById(zald).className=zaqc;return;}
if(zbhq(zri)){document.getElementById(zaky).innerHTML=zte("create_symbol_restrict");document.getElementById(zakt).focus();return;}
var zbrs=zkm;if(zri.toString()==zbrq.toString()){if(zbml){var zbrt=document.getElementById(zbml);zbrs=zbrt.getAttribute("obj_path");}
if(zbrs==zbrr){document.getElementById(zald).setAttribute(zapz,"1");document.getElementById(zald).className=zaqc;return;}
}document.getElementById(zald).removeAttribute(zapz);document.getElementById(zald).className=zaqb;}
catch(zmk){}};function zbru(event){zbrp();};var zbml=null;function zbrv(parentNode,zbrw,zbrx,zbry){try{if(zbry&&zbry.length>zarr){zbry=zbry.substring(0,zarr-3)+"...";}
var zbrz=document.createElement("ul");var zbsa=document.createElement("li");zbrz.setAttribute("obj_path",zbrw);zbsa.setAttribute("obj_path",zbrw);zbsa.setAttribute("id",zbrw);if(zbrx==true){zbsa.setAttribute("class","cl");}
var zbct=document.createElement("div");zbct.setAttribute("obj_path",zbrw);var zpb=document.createElement("p");zpb.setAttribute("id","p_href"+zbrw);zpb.setAttribute("obj_path",zbrw);var zbsb=document.createElement("a");zbsb.setAttribute("href","#");zbsb.setAttribute("class","sc");zbsb.setAttribute("close_state",zbrx);zbsb.addEventListener("click",zbsc,false);var zbsd=zbrx==true?zahb:zaha;zbsb.innerHTML="<img src='"+zbsd+"' class='i' />";zpb.appendChild(zbsb);var zbse=document.createElement("a");zbse.setAttribute("href","#");zbse.setAttribute("class","nodetext");zbse.setAttribute("obj_path",zbrw);zbse.setAttribute("id","a_href"+zbrw);zbse.addEventListener("click",zbsf,false);var zbsg=zbrx==true?zahn:zahn;zbse.innerHTML="<img src='"+zbsg+"' class='i2' />"+zbry;zpb.appendChild(zbse);zbct.appendChild(zpb);zbsa.appendChild(zbct);zbrz.appendChild(zbsa);parentNode.appendChild(zbrz);return zbrz;}
catch(zmk){}};function zbmf(arr,zbsh,zuu){try{zbml=null;var zbsi=document.getElementById(zuu);zbrv(zbsi,zgw,false,"Home");for(var zne=0;zne<arr.length;++zne){var zbrw=arr[zne];if(zbrw=="Home"){continue;}
var zbsj=zbrw.split(zgw);var zbsk=zgw;for(var zbsl=1;zbsl<zbsj.length;++zbsl){var zbsm=document.getElementById(zbsk);zbsk=zbsk+zgw+zbsj[zbsl];if(zbsk.startsWith("//")){zbsk=zbsk.substr(1);}
var zbsn=document.getElementById(zbsk);if(!zbsn){zbrv(zbsm,zbsk,true,zbsj[zbsl]);}
}}var zbso=document.getElementsByTagName("li");if(zbso!=null){var zbet=zbso.length;for(var zoy=0;zoy<zbet;zoy++){var zbsa=zbso[zoy];if(zbsa.children.length==1){if(zbsa.firstChild.firstChild.firstChild){zbsa.firstChild.firstChild.firstChild.innerHTML=zkm;}
}if(zbsh==zbsa.getAttribute("id")){var zbsp=zbsa['firstChild']['firstChild'];var zbsq=zbsp.childNodes[0];zbsf.call(zbsp);zbsr(zbsa);}
}}}catch(zmk){}};function zbss(){var zbso=document.getElementsByTagName("li");if(zbso!=null){var zbet=zbso.length;for(var zoy=0;zoy<zbet;zoy++){var zbsa=zbso[zoy];if(zbsa.children.length==1){if(zbsa.firstChild.firstChild.firstChild){zbsa.firstChild.firstChild.firstChild.innerHTML=zkm;}
}else{if(zbsa.firstChild.firstChild.firstChild&&zbsa.firstChild.firstChild.firstChild.getAttribute('close_state')=='true'){var zbst="<img src='"+zahb+"' class='i' />";zbsa.firstChild.firstChild.firstChild.innerHTML=zbst;}
if(zbsa.firstChild.firstChild.firstChild&&zbsa.firstChild.firstChild.firstChild.getAttribute('close_state')=='false'){var zbst="<img src='"+zaha+"' class='i' />";zbsa.firstChild.firstChild.firstChild.innerHTML=zbst;}
}}}};function zbsf(){try{if(zbml){var zbrt=document.getElementById(zbml);zbrt.style.fontSize="11px";zbrt.style.fontWeight="normal";zbrt.style.background="white";}
this.style.fontSize="11px";this.style.fontWeight="bold";this.style.background="#f3f3f3";zbml=this.id;zbrp();return false;}
catch(zmk){}};function zbsc(){if(this.getAttribute("close_state")=="true"){this.innerHTML="<img src='"+zaha+"' class='i' />";this.parentNode.parentNode.parentNode.className='';this.nextSibling.firstChild.setAttribute("src",zahn);this.setAttribute("close_state",false);}
else{this.innerHTML="<img src='"+zahb+"' class='i' />";this.parentNode.parentNode.parentNode.className='cl';this.nextSibling.firstChild.setAttribute("src",zahn);this.setAttribute("close_state",true);}
return false;};function zbsr(zbsu){if(zbsu.tagName&&zbsu.tagName.toLowerCase()=="li"){zbsu.className='';if(zbsu.children.length>1){zbsu.firstChild.firstChild.firstChild.innerHTML="<img src='"+zaha+"' class='i' />";zbsu.firstChild.firstChild.firstChild.setAttribute("close_state",false);}
}if(zbsu.parentNode!=null){zbsr(zbsu.parentNode);}
return;};function zbhq(zmc){if(zmc==zkm||zmc==null){return false;}
if(zmc.indexOf("/")!=-1||zmc.indexOf("<")!=-1||zmc.indexOf(">")!=-1||zmc.indexOf(String.fromCharCode(92))!=-1||zmc.indexOf("?")!=-1||zmc.indexOf(":")!=-1||zmc.indexOf(String.fromCharCode(34))!=-1||zmc.indexOf("*")!=-1||zmc.indexOf("|")!=-1){return true;}
return false;};function zbrj(zauz){try{var zbsv=zahn;if(zauz.m_Type==RfObjectType.RFTYPE_PASSCARD){zbsw=zauz.znf==RfObjectMode.RF_OBJ_MODE_DEF?zte("new_passcard_name"):zte("new_bookmark_name");zbsv=zauz.znf==RfObjectMode.RF_OBJ_MODE_DEF?zaho:zahr;}
else if(zauz.m_Type==RfObjectType.RFTYPE_IDENTITY){zbsw=zauz.znf==RfObjectMode.RF_OBJ_MODE_DEF?zte("new_identity_name"):zte("new_contact_name");zbsv=zauz.znf==RfObjectMode.RF_OBJ_MODE_DEF?zahl:zaht;}
else if(zauz.m_Type==RfObjectType.RFTYPE_SAFENOTE){zbsw=zte("new_safenote_name");zbsv=zahv;}
return{text:zbsw,zbrk:zbsv};}catch(zmk){}};function zbrg(zbba,zauu){try{var zazq=zazr();var zauz=zbba.zyi;var zbhx=zbba.parentId;zatq("n_popup_renamefld_width",zfl,zfm);zatr({"s_html":zaqt,"sTitle":zte("rename_folder"),"b_pushtoArrays":false,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});setTimeout(function(){zatr({"s_html":$("#rffolder_rename_section_div").html(),"sTitle":zte("rename_folder"),"b_pushtoArrays":true,"b_show_title":true,"b_show_back":true,"searchObj":{"bShowSearchBox":false,"isSearchResults":false,"s_searchquery":zkm}
,"parentId":zkm});document.getElementById(zalh).innerHTML=zkm;document.getElementById(zall).setAttribute(zapo,zauu);document.getElementById(zall).setAttribute("defaultValue",zauz.m_sName);document.getElementById(zall).setAttribute(zaqh,zbhx);document.getElementById(zall).value=zauz.m_sName;document.getElementById(zall).focus();zbsx();}
,zask);}catch(zmk){}};function zbsy(event){try{document.getElementById(zalh).innerHTML=zkm;var zbsz=document.getElementById(zall).value;if(zbsz==null||zbsz==zkm){document.getElementById(zall).focus();return;}
if(zbhq(zbsz)){document.getElementById(zalh).innerHTML=zte("create_symbol_restrict");document.getElementById(zall).focus();return;}
if(zbsz.length>zarq){document.getElementById(zalh).innerHTML="Name is too long!";return;}
var zauu=document.getElementById(zall).getAttribute(zapo);var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;var zph=zauz.zpk;var zblk=zph.lastIndexOf("/");if(zblk!=-1){zph=zph.substr(0,zblk+1);}
zatx(true,zali,[zalj,zalk],zall);setTimeout(function(){var zaty=new Object();zaty[zct]=zauz;zaty[zci]=zauu;zaty[zce]=zarn;zaty[zch]="";zaty[zcn]="";zaty[zcg]=zbsz;zaty[zcm]=zph+zbsz;zaty["b_cut_copy"]=false;var zatz=zrv().zxz(zaty);zbgm(zatz);return;}
,zask);}catch(zmk){zatx(false,zali,[zalj,zalk],null);}
};function zbgm(zatz){try{if(!zatz){return;}var zato=zatz[zbu];var zauz=zato[zct];var zbta=[];var zbtb=zkm;var zbtc=null;var zbtd=null;var zaut=0;var zbte=zkm;if(zauz.m_Type==RfObjectType.RFTYPE_FOLDER){zbta.push(zalj);zbta.push(zalk);zbtb=zali;zbtc=document.getElementById(zall);zbtd=document.getElementById(zalh);zaut=zafl.rename_folder;zbte=zall;}
else if(zauz.m_Type==RfObjectType.RFTYPE_PASSCARD||zauz.m_Type==RfObjectType.RFTYPE_SAFENOTE||zauz.m_Type==RfObjectType.RFTYPE_IDENTITY){zbta.push(zald);zbta.push(zale);zbta.push(zaks);zbtb=zalb;zbtc=document.getElementById(zakt);zbtd=document.getElementById(zaky);zaut=zafl.rename_passcard;zbte=zakt;}
zatx(false,zbtb,zbta,null);if(zatz[zcv]==true){zbqo(zauz,zato[zch],zato[zcn],zato[zcg],zato[zcm],false);zbtf(true,zbte);return;}
var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=zbtc;zave[zbp]=zbtd;zave[zby]="rf_RenameRfObjectResponse";zave[zct]=zauz;zave[zci]=zato[zci];zave[zaz]=zafl.rename_folder;zavf(zave);}
catch(zmk){}};function zbtf(zawd,zawe){var zacg=zawd||false;zaul(zacg,zawe,"",true);}
;function zbtg(zaun){zbth();zaun=zaun||window.event;var target=(zaun.target)?zaun.target:zaun.scrElement;var zauo=(zaun.charCode)?zaun.charCode:((zaun.zaup)?zaun.zaup:zaun.keyCode);if(zauo==zia){zbsy();return;}
};function zbti(event){zbth();};function zbth(){document.getElementById(zalh).innerHTML=zkm;var zri=document.getElementById(zall).value;var zbrq=document.getElementById(zall).getAttribute("defaultValue");if(zri.toString()==zkm){document.getElementById(zalj).setAttribute(zapz,"1");document.getElementById(zalj).className=zaqc;return;}
if(zri.toString()==zbrq.toString()){document.getElementById(zalj).setAttribute(zapz,"1");document.getElementById(zalj).className=zaqc;return;}
if(zbhq(zri)){document.getElementById(zalh).innerHTML=zte("create_symbol_restrict");document.getElementById(zall).focus();return;}
document.getElementById(zalj).removeAttribute(zapz);document.getElementById(zalj).className=zaqb;}
;function zbtj(){try{zbtk(false);document.getElementById(zakw).value=zkm;document.getElementById(zakw).focus();return;}
catch(zmk){}};function zbtk(zbtl){try{document.getElementById(zaky).innerHTML=zkm;var zbtm=zbtl==false?zaqe:"table-row";document.getElementById("rfpcard_rename_section_btns_row").style.display=zbtm;document.getElementById("rfpcard_rename_section_tree_row").style.display=zbtm;document.getElementById("rfpcard_rename_section_input_row").style.display=zbtm;var zbtn=zbtl==true?zaqe:"table-row";document.getElementById("rf_new_folder_part_btns_row").style.display=zbtn;document.getElementById("rfpcard_createfolder_section_input_row").style.display=zbtn;if(!zbtl){document.getElementById(zaks).style.visibility="hidden";document.getElementById(zakq).innerText=zte("create_folder");document.getElementById(zakq).style.background="url('"+zahn+"') no-repeat";document.getElementById(zakr).innerText=zte("folder_name");}
else{var zauu=document.getElementById(zakt).getAttribute(zapo);var zbba=zarf.znx(zauu);if(zbba==null){return;}
var zauz=zbba.zyi;var zbri=zbrj(zauz);document.getElementById(zakq).style.background="url('"+zbri.zbrk+"') no-repeat";document.getElementById(zakq).innerText=zte("rename_passcard");document.getElementById(zakr).innerText=zbri.text+":";document.getElementById(zaks).style.visibility="visible";}
}catch(zmk){}};function zbto(event){try{var zbsz=document.getElementById(zakw).value;if(zbsz==null||zbsz==zkm){document.getElementById(zaky).innerHTML=zkm;document.getElementById(zakw).focus();return;}
if(zbhq(zbsz)){document.getElementById(zaky).innerHTML=zte("create_symbol_restrict");document.getElementById(zakw).focus();return;}
var zbtp=document.getElementById(zbml).getAttribute("obj_path");zbtp=zbtp+zgw+zbsz;if(zbtp.startsWith("//")){zbtp=zbtp.substr(1);}
zatx(true,zalc,[zakz,zala],zakw);setTimeout(function(){var zaty=new Object();zaty["relative_path"]=zbtp;zaty["folder_name"]=zbsz;zaty[zce]=zarn;var zatz=zrv().zyf(zaty);zbgr(zatz);}
,500);}catch(zmk){zatx(false,zalc,[zakz,zala],null);}
};function zbgr(zatz){try{if(!zatz||zatz==undefined){return;}
zatx(false,zalc,[zakz,zala],null);if(zatz[zcv]==true){var zbtq=zatz[zbu]["relative_path"];var zbtr=zatz[zbu]["folder_name"];var zbsm=document.getElementById(zbml);zbsm=zbsm.parentNode.parentNode.parentNode;var zbsu=zbrv(zbsm,zbtq,true,zbtr);zbss();zbsr(zbsu);zbtk(true);document.getElementById(zakt).setAttribute("force_refresh",true);return;}
var zave=new Object();zave[zbv]=zatz[zbv];zave[zbw]=zatz[zbw];zave[zbo]=document.getElementById(zakw);zave[zbp]=document.getElementById(zaky);zave[zby]="rf_createnewfolder_OKClick";zave[zaz]=zafl.create_new_folder;zave[zci]=0;zavf(zave);}
catch(zmk){}};function zbts(event){try{zbtk(true);document.getElementById(zakt).focus();}
catch(zmk){}};function zbtt(){zbtu();};function zbtu(){try{document.getElementById(zaky).innerHTML=zkm;var zbsz=document.getElementById(zakw).value;if(zbhq(zbsz)){document.getElementById(zaky).innerHTML=zte("create_symbol_restrict");document.getElementById(zakw).focus();return;}
}catch(zmk){}};function zbtv(zaun){zbtu();zaun=zaun||window.event;var target=(zaun.target)?zaun.target:zaun.scrElement;var zauo=(zaun.charCode)?zaun.charCode:((zaun.zaup)?zaun.zaup:zaun.keyCode);if(zauo==zia){zbto(zaun);}
return;};
